#!/bin/bash

set -e  # 遇到错误时停止脚本执行

# ANSI 颜色代码
RED='\033[1;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}=====================================${NC}"
echo -e "${GREEN} Installation Successful!${NC}"
echo -e "${YELLOW} Please run '${RED}Zsh-install${YELLOW}' to install the shell.${NC}"
echo -e "${GREEN}=====================================${NC}"